version: '3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: reisquaza
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: secretkey
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:5432/secretkey
      - DATABASE_USERNAME=reisquaza
      - DATABASE_PASSWORD=1234
volumes:
  postgres-data: